CREATE TABLE CLIENTE
(
  DNI        VARCHAR2(9)                   NOT NULL,
  NOMBRE     VARCHAR2(30)                  NOT NULL,
  APELLIDO   VARCHAR2(30)                  NOT NULL,
  EDAD       INTEGER                            NOT NULL,
  DIRECCION  VARCHAR2(30),
  CODPOSTAL  INTEGER,
  LOCALIDAD  VARCHAR2(30),
  TELEFONO   INTEGER
);

CREATE UNIQUE INDEX PK_CLIENTE ON CLIENTE(DNI);

ALTER TABLE CLIENTE ADD (CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI));

CREATE TABLE USUARIOS
(
  USUARIO   VARCHAR2(8)                    NOT NULL,
  PASSWORD  VARCHAR2(8)                    NOT NULL
);

CREATE UNIQUE INDEX PK_USUARIOS ON USUARIOS(USUARIO);

ALTER TABLE USUARIOS ADD (CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO));

INSERT INTO USUARIOS (USUARIO, PASSWORD) VALUES ('usu', 'usu');

commit;
