CREATE TABLE CLIENTES
(
  DNI        VARCHAR(9)                   NOT NULL,
  NOMBRE     VARCHAR(30)                  NOT NULL,
  APELLIDO   VARCHAR(30)                  NOT NULL,
  EDAD       INTEGER                            NOT NULL,
  DIRECCION  VARCHAR(30),
  CODPOSTAL  INTEGER,
  LOCALIDAD  VARCHAR(30),
  TELEFONO   INTEGER
);

CREATE UNIQUE INDEX PK_CLIENTES ON CLIENTES(DNI);

ALTER TABLE CLIENTES ADD (CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI));

CREATE TABLE USUARIOS
(
  USUARIO   VARCHAR(8)                    NOT NULL,
  PASSWORD  VARCHAR(8)                    NOT NULL
);

CREATE UNIQUE INDEX PK_USUARIOS ON USUARIOS(USUARIO);

ALTER TABLE USUARIOS ADD (CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO));

CREATE TABLE PEDIDOS
(
  DNI            VARCHAR(9)               NOT NULL,
  NUMPEDIDO      INTEGER                        NOT NULL,
  DETALLEPEDIDO  VARCHAR(100)             NOT NULL
);

CREATE UNIQUE INDEX PK_PEDIDOS ON PEDIDOS(DNI, NUMPEDIDO);

ALTER TABLE PEDIDOS ADD (CONSTRAINT PK_PEDIDOS PRIMARY KEY (DNI, NUMPEDIDO));

INSERT INTO USUARIOS (USUARIO, PASSWORD) VALUES ('usu', 'usu');

commit;

